# generated by datamodel-codegen:
#   filename:  violations.json
#   timestamp: 2024-11-11T17:49:08+00:00

from __future__ import annotations


from sqlalchemy import Table, Column, String, DateTime
from database.database import metadata, json_type


violations_table = Table(
    "violations",
    metadata,
    Column("description", String, nullable=False),
    Column("severity", String, nullable=False),
    Column("type", String, nullable=False),
    Column("infected_components", json_type, nullable=False),
    Column("created", DateTime, nullable=False),
    Column("watch_name", String, nullable=False),
    Column("issue_id", String, nullable=False),
    Column("violation_details_url", String, nullable=False),
    Column("impacted_artifacts", json_type, nullable=False),
)

violations_hwm_table = Table(
    "violations_hwm", metadata, Column("created_hwm", DateTime, nullable=False)
)
