# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2024-11-12T20:59:45+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class LOCALItem(BaseModel):
    key: str
    packageType: str
    description: str
    notes: str
    includesPattern: str
    excludesPattern: str
    repoLayoutRef: Optional[str] = None
    signedUrlTtl: int
    priorityResolution: bool
    environments: List[str]
    blackedOut: bool
    propertySets: List[str]
    archiveBrowsingEnabled: bool
    xrayDataTtl: int
    downloadRedirect: bool
    cdnRedirect: bool
    xrayIndex: bool
    rclass: str
    projectKey: Optional[str] = None
    forceNugetAuthentication: Optional[bool] = None
    enableNormalizedVersion: Optional[bool] = None
    maxUniqueSnapshots: Optional[int] = None
    debianTrivialLayout: Optional[bool] = None
    ddebSupported: Optional[bool] = None
    optionalIndexCompressionFormats: Optional[List[str]] = None
    checksumPolicyType: Optional[str] = None
    handleReleases: Optional[bool] = None
    handleSnapshots: Optional[bool] = None
    snapshotVersionBehavior: Optional[str] = None
    suppressPomConsistencyChecks: Optional[bool] = None
    dockerApiVersion: Optional[str] = None
    blockPushingSchema1: Optional[bool] = None
    maxUniqueTags: Optional[int] = None
    dockerTagRetention: Optional[int] = None
    encryptStates: Optional[bool] = None
    cargoAnonymousAccess: Optional[bool] = None
    cargoInternalIndex: Optional[bool] = None
    forceConanAuthentication: Optional[bool] = None
    terraformType: Optional[str] = None
    enableComposerV1Indexing: Optional[bool] = None
    calculateYumMetadata: Optional[bool] = None
    enableFileListsIndexing: Optional[bool] = None
    yumRootDepth: Optional[int] = None
    yumGroupFileNames: Optional[str] = None


class Statistics(BaseModel):
    enabled: bool


class Properties(BaseModel):
    enabled: bool


class Source(BaseModel):
    originAbsenceDetection: bool


class ContentSynchronisation(BaseModel):
    enabled: bool
    statistics: Statistics
    properties: Properties
    source: Source


class REMOTEItem(BaseModel):
    key: str
    packageType: str
    description: str
    notes: str
    includesPattern: str
    excludesPattern: str
    repoLayoutRef: Optional[str] = None
    signedUrlTtl: int
    priorityResolution: bool
    environments: List[str]
    url: str
    username: str
    password: str
    disableProxy: bool
    hardFail: bool
    offline: bool
    blackedOut: bool
    storeArtifactsLocally: bool
    socketTimeoutMillis: int
    localAddress: str
    retrievalCachePeriodSecs: int
    assumedOfflinePeriodSecs: int
    missedRetrievalCachePeriodSecs: int
    metadataRetrievalTimeoutSecs: int
    unusedArtifactsCleanupPeriodHours: int
    shareConfiguration: bool
    synchronizeProperties: bool
    propertySets: List[str]
    archiveBrowsingEnabled: bool
    listRemoteFolderItems: bool
    allowAnyHostAuth: bool
    enableCookieManagement: bool
    propagateQueryParams: bool
    blockMismatchingMimeTypes: bool
    mismatchingMimeTypesOverrideList: Optional[str] = None
    bypassHeadRequests: bool
    disableUrlNormalization: bool
    contentSynchronisation: ContentSynchronisation
    sendContext: bool
    passThrough: bool
    curated: bool
    retrieveSha256FromServer: bool
    xrayDataTtl: int
    downloadRedirect: bool
    xrayIndex: bool
    rclass: str
    handleReleases: Optional[bool] = None
    handleSnapshots: Optional[bool] = None
    suppressPomConsistencyChecks: Optional[bool] = None
    remoteRepoChecksumPolicyType: Optional[str] = None
    fetchJarsEagerly: Optional[bool] = None
    fetchSourcesEagerly: Optional[bool] = None
    maxUniqueSnapshots: Optional[int] = None
    rejectInvalidJars: Optional[bool] = None
    vcsType: Optional[str] = None
    composerRegistryUrl: Optional[str] = None
    vcsGitProvider: Optional[str] = None
    pyPIRegistryUrl: Optional[str] = None
    pyPIRepositorySuffix: Optional[str] = None
    externalDependenciesEnabled: Optional[bool] = None
    externalDependenciesPatterns: Optional[List[str]] = None
    projectKey: Optional[str] = None
    forceNugetAuthentication: Optional[bool] = None
    enableNormalizedVersion: Optional[bool] = None
    downloadContextPath: Optional[str] = None
    feedContextPath: Optional[str] = None
    v3FeedUrl: Optional[str] = None
    symbolServerUrl: Optional[str] = None
    dockerApiVersion: Optional[str] = None
    blockPushingSchema1: Optional[bool] = None
    dockerProjectId: Optional[str] = None
    enableTokenAuthentication: Optional[bool] = None
    forceConanAuthentication: Optional[bool] = None
    terraformRegistryUrl: Optional[str] = None
    terraformProvidersUrl: Optional[str] = None
    ddebSupported: Optional[bool] = None
    cargoAnonymousAccess: Optional[bool] = None
    cargoInternalIndex: Optional[bool] = None
    gitRegistryUrl: Optional[str] = None
    remoteRepoLayoutRef: Optional[str] = None
    podsCdnUrl: Optional[str] = None
    podsSpecsRepoUrl: Optional[str] = None
    podsForceModifyIndex: Optional[bool] = None
    forceP2Authentication: Optional[bool] = None


class VIRTUALItem(BaseModel):
    key: str
    packageType: str
    description: str
    notes: str
    includesPattern: str
    excludesPattern: str
    repoLayoutRef: Optional[str] = None
    signedUrlTtl: int
    environments: List[str]
    repositories: List[str]
    hideUnauthorizedResources: bool
    artifactoryRequestsCanRetrieveRemoteArtifacts: bool
    externalDependenciesEnabled: Optional[bool] = None
    externalDependenciesPatterns: Optional[List[str]] = None
    virtualRetrievalCachePeriodSecs: Optional[int] = None
    rclass: str
    defaultDeploymentRepo: Optional[str] = None
    keyPair: Optional[str] = None
    pomRepositoryReferencesCleanupPolicy: Optional[str] = None
    forceMavenAuthentication: Optional[bool] = None
    projectKey: Optional[str] = None
    forceNugetAuthentication: Optional[bool] = None
    enableNormalizedVersion: Optional[bool] = None
    dockerApiVersion: Optional[str] = None
    resolveDockerTagsByTimestamp: Optional[bool] = None
    cachingLocalForeignLayersEnabled: Optional[bool] = None
    externalDependenciesRemoteRepo: Optional[str] = None
    forceConanAuthentication: Optional[bool] = None
    useNamespaces: Optional[bool] = None
    ddebSupported: Optional[bool] = None
    debianDefaultArchitectures: Optional[str] = None
    optionalIndexCompressionFormats: Optional[List[str]] = None
    forceP2Authentication: Optional[bool] = None
    p2Urls: Optional[List[str]] = None


class Member(BaseModel):
    url: str
    enabled: bool
    mode: Optional[str] = None


class FEDERATEDItem(BaseModel):
    key: str
    packageType: str
    description: str
    notes: str
    includesPattern: str
    excludesPattern: str
    repoLayoutRef: str
    signedUrlTtl: int
    priorityResolution: bool
    environments: List[str]
    checksumPolicyType: Optional[str] = None
    handleReleases: Optional[bool] = None
    handleSnapshots: Optional[bool] = None
    maxUniqueSnapshots: Optional[int] = None
    snapshotVersionBehavior: Optional[str] = None
    suppressPomConsistencyChecks: Optional[bool] = None
    blackedOut: bool
    propertySets: List[str]
    archiveBrowsingEnabled: bool
    members: List[Member]
    disableProxy: bool
    downloadRedirect: bool
    cdnRedirect: bool
    xrayIndex: bool
    xrayDataTtl: int
    rclass: str
    debianTrivialLayout: Optional[bool] = None
    ddebSupported: Optional[bool] = None
    optionalIndexCompressionFormats: Optional[List[str]] = None
    projectKey: Optional[str] = None
    forceNugetAuthentication: Optional[bool] = None
    enableNormalizedVersion: Optional[bool] = None
    dockerApiVersion: Optional[str] = None
    blockPushingSchema1: Optional[bool] = None
    maxUniqueTags: Optional[int] = None
    dockerTagRetention: Optional[int] = None


class RELEASEBUNDLEItem(BaseModel):
    key: str
    packageType: str
    description: str
    notes: str
    includesPattern: str
    excludesPattern: str
    repoLayoutRef: Optional[str] = None
    signedUrlTtl: int
    priorityResolution: bool
    environments: List
    blackedOut: bool
    propertySets: List[str]
    archiveBrowsingEnabled: bool
    xrayDataTtl: int
    downloadRedirect: bool
    cdnRedirect: bool
    xrayIndex: bool
    rclass: str


class ArtifactRepos(BaseModel):
    LOCAL: List[LOCALItem]
    REMOTE: List[REMOTEItem]
    VIRTUAL: List[VIRTUALItem]
    FEDERATED: List[FEDERATEDItem]
    RELEASE_BUNDLE: List[RELEASEBUNDLEItem]
